### ISSUE TITLE
[Config Issue] Wrong character used for coordinates

### ISSUE THREAD

**Issue by RichardPaulAstley** [berichan/PLAWarper#1]
Hi o/
First, huge thanks for the tool. It'll help us a lot for RNG Researches purposes for PLA.
However, i'm getting an issue right now with my configuration.

So my PC is in French (I think that's the issues) and coordinates aren't stored the same way.
To do simple my positions.txt looks like this : 

`338,702,106,8714,675,3433`

I guess it's because it's configurated to saves coordinates like we setup in French.
However as soon as I close the tool, I can't get the coordinates back, or they're shrunk to "338,702,106"

So I wanted to edit the config by editing the positions (i even asked for some clean position.txt files), I get an error saying that the entry output is wrong, and loads the tool without any coordinates

So if we could have a fix for that.
Thanks again o/

**Comment by berichan** [comment]
Can you confirm whether or not the changes provided by @SteveCookTU address this issue? I've attached a build below.
[PLAWarper.zip](https://github.com/berichan/PLAWarper/files/7995905/PLAWarper.zip)

**Comment by RichardPaulAstley** [comment]
@SteveCookTU is a friend that works with me, so he did the fix for me and gave me a build.
I tried it, it works fine !

Thanks again <3

**Comment by berichan** [comment]
👍
